Organize test
nyggus/makepackage pull request #22
Opened 2023-06-01 18:31 UTC by patrickboateng

Redesigned tests to use pytest for testing.

2023-06-02 06:55 UTC, nyggus requested changes
Great work! I added three comments here, and one more thing: please remove all the unnecessary files from the `tests/` folder.

2023-06-02 06:55 UTC, nyggus commented on tests/conftest.py
>  def files_no_CLI() -> Iterator[Dict[str, List[str]]]:
The type hint is now incorrect. Since the fixture returns a dict, `Iterator` should be removed.

2023-06-02 06:55 UTC, nyggus commented on tests/conftest.py
>  def files_with_CLI() -> Iterator[Dict[str, List[str]]]:
Likewise.

2023-06-02 06:55 UTC, nyggus commented on tests/test_makepackage.py
> +def test_pkg_files_with_CLI(tmp_path: Path, files_with_CLI: Dict[str, List[str]]):
In this version, it does not make much sense to write two test functions, one for folders and one for files, as they create the same environment. Hence, please join them. So, we will have two test functions: one without and another with CLI.

2023-06-02 07:01 UTC, patrickboateng commented
oh okay very good, I'm on it.

2023-06-02 18:43 UTC, patrickboateng commented
I have applied all necessary changes, kindly review and give me feedback.

2023-06-07 02:15 UTC, nyggus approved these changes
Nice!

2023-06-07 02:15 UTC, merged