Move to pyproject
nyggus/makepackage pull request #26
Opened 2023-09-05 21:26 UTC by patrickboateng

I have moved the project's configuration from `setup.py` to `pyproject.toml`.

2023-09-12 11:49 UTC, nyggus requested changes

2023-09-12 11:49 UTC, nyggus commented on tests/test_makepackage.py
> -def test_pkg_no_CLI(
Did you run the tests in Python 3.11? The tests did pass in Python 3.9, but both failed in Python 3.11, with the same error:
<img width="498" alt="image" src="https://github.com/nyggus/makepackage/assets/39629775/db692495-bec7-4143-b2bf-f5784ece1644">

2023-09-13 19:22 UTC, patrickboateng commented
Oh my bad, I think I will need a github action setup on my repo then, I currently have `python 3.10` on my machine.

2023-09-13 19:49 UTC, patrickboateng commented
Oh my bad, I currently have only `python 3.10` on my machine, I would have to install multiple versions of python on my machine and use `tox` for the testing instead. If I may ask, how do you test your python packages against other python versions on your local machine?

2023-12-12 10:44 UTC, merged